apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  annotations:
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: incibe-svsm_ts-mysql-01
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
